export const machines = [
  {
    id: '1',
    name: 'Main Lobby',
    location: 'Purdue Union – 1st Floor',
    address: '101 N Grant St, West Lafayette, IN 47907',
    buildingNotes: 'Enter through the main front doors on Grant St. The machine is immediately on your right as you walk in, next to the information desk. Parking available in the Union lot off Northwestern Ave.',
    status: 'online',
    revenueToday: 47.50,
    itemsInStock: 82,
    alerts: 2,
    slots: [
      { id: 'A1', name: 'Lay\'s Classic', stock: 8, capacity: 10, price: 1.75, reorderUrl: 'https://www.costco.com' },
      { id: 'A2', name: 'Doritos Nacho', stock: 2, capacity: 10, price: 1.75, reorderUrl: 'https://www.costco.com' },
      { id: 'A3', name: 'Cheez-Its', stock: 0, capacity: 10, price: 1.50, reorderUrl: 'https://www.costco.com' },
      { id: 'A4', name: 'Peanut Butter Crackers', stock: 9, capacity: 10, price: 1.25, reorderUrl: 'https://www.costco.com' },
      { id: 'B1', name: 'Water (16oz)', stock: 5, capacity: 12, price: 1.50, reorderUrl: 'https://www.costco.com' },
      { id: 'B2', name: 'Gatorade Blue', stock: 7, capacity: 12, price: 2.25, reorderUrl: 'https://www.costco.com' },
      { id: 'B3', name: 'Diet Coke', stock: 3, capacity: 12, price: 1.75, reorderUrl: 'https://www.costco.com' },
      { id: 'B4', name: 'Red Bull', stock: 1, capacity: 8, price: 3.50, reorderUrl: 'https://www.costco.com' },
      { id: 'C1', name: 'Snickers', stock: 6, capacity: 10, price: 1.75, reorderUrl: 'https://www.costco.com' },
      { id: 'C2', name: 'Kit Kat', stock: 10, capacity: 10, price: 1.75, reorderUrl: 'https://www.costco.com' },
      { id: 'C3', name: 'Skittles', stock: 4, capacity: 10, price: 1.50, reorderUrl: 'https://www.costco.com' },
      { id: 'C4', name: 'Trail Mix', stock: 8, capacity: 8, price: 2.00, reorderUrl: 'https://www.costco.com' },
    ],
    weekSales: [
      { day: 'Mon', sales: 18 },
      { day: 'Tue', sales: 24 },
      { day: 'Wed', sales: 31 },
      { day: 'Thu', sales: 27 },
      { day: 'Fri', sales: 38 },
      { day: 'Sat', sales: 14 },
      { day: 'Sun', sales: 9 },
    ],
    peakHours: [
      { hour: '8am', sales: 12 },
      { hour: '10am', sales: 8 },
      { hour: '12pm', sales: 27 },
      { hour: '2pm', sales: 19 },
      { hour: '4pm', sales: 22 },
      { hour: '6pm', sales: 14 },
      { hour: '8pm', sales: 6 },
    ],
    earnings: {
      monthToDate: 1284.50,
      lastMonth: 1102.00,
      thisWeek: 312.75,
      avgPerDay: 41.43,
      itemsSoldMonth: 734,
      avgSalePrice: 1.75,
      recentSales: [
        { item: 'Gatorade Blue', qty: 1, time: '2:43 PM', revenue: 2.25 },
        { item: 'Doritos Nacho', qty: 1, time: '2:31 PM', revenue: 1.75 },
        { item: 'Snickers', qty: 2, time: '1:58 PM', revenue: 3.50 },
        { item: 'Water (16oz)', qty: 1, time: '1:22 PM', revenue: 1.50 },
        { item: 'Red Bull', qty: 1, time: '12:47 PM', revenue: 3.50 },
        { item: 'Lay\'s Classic', qty: 1, time: '12:30 PM', revenue: 1.75 },
        { item: 'Kit Kat', qty: 3, time: '11:55 AM', revenue: 5.25 },
      ],
    },
  },
  {
    id: '2',
    name: 'Engineering Hall',
    location: 'WALC – 3rd Floor',
    address: '516 Northwestern Ave, West Lafayette, IN 47907',
    buildingNotes: 'Enter WALC from Northwestern Ave. Take the elevator or stairs to the 3rd floor. Turn left out of the elevator — the machine is at the end of the hallway near the study rooms. Street parking on Northwestern or use the engineering garage.',
    status: 'online',
    revenueToday: 63.25,
    itemsInStock: 104,
    alerts: 1,
    slots: [
      { id: 'A1', name: 'Lay\'s Classic', stock: 9, capacity: 10, price: 1.75, reorderUrl: 'https://www.costco.com' },
      { id: 'A2', name: 'Doritos Nacho', stock: 7, capacity: 10, price: 1.75, reorderUrl: 'https://www.costco.com' },
      { id: 'A3', name: 'Cheez-Its', stock: 10, capacity: 10, price: 1.50, reorderUrl: 'https://www.costco.com' },
      { id: 'A4', name: 'Peanut Butter Crackers', stock: 1, capacity: 10, price: 1.25, reorderUrl: 'https://www.costco.com' },
      { id: 'B1', name: 'Water (16oz)', stock: 12, capacity: 12, price: 1.50, reorderUrl: 'https://www.costco.com' },
      { id: 'B2', name: 'Gatorade Blue', stock: 10, capacity: 12, price: 2.25, reorderUrl: 'https://www.costco.com' },
      { id: 'B3', name: 'Diet Coke', stock: 8, capacity: 12, price: 1.75, reorderUrl: 'https://www.costco.com' },
      { id: 'B4', name: 'Red Bull', stock: 5, capacity: 8, price: 3.50, reorderUrl: 'https://www.costco.com' },
      { id: 'C1', name: 'Snickers', stock: 9, capacity: 10, price: 1.75, reorderUrl: 'https://www.costco.com' },
      { id: 'C2', name: 'Kit Kat', stock: 8, capacity: 10, price: 1.75, reorderUrl: 'https://www.costco.com' },
      { id: 'C3', name: 'Skittles', stock: 7, capacity: 10, price: 1.50, reorderUrl: 'https://www.costco.com' },
      { id: 'C4', name: 'Trail Mix', stock: 8, capacity: 8, price: 2.00, reorderUrl: 'https://www.costco.com' },
    ],
    weekSales: [
      { day: 'Mon', sales: 22 },
      { day: 'Tue', sales: 35 },
      { day: 'Wed', sales: 41 },
      { day: 'Thu', sales: 33 },
      { day: 'Fri', sales: 29 },
      { day: 'Sat', sales: 5 },
      { day: 'Sun', sales: 3 },
    ],
    peakHours: [
      { hour: '8am', sales: 18 },
      { hour: '10am', sales: 22 },
      { hour: '12pm', sales: 31 },
      { hour: '2pm', sales: 28 },
      { hour: '4pm', sales: 15 },
      { hour: '6pm', sales: 4 },
      { hour: '8pm', sales: 2 },
    ],
    earnings: {
      monthToDate: 1876.00,
      lastMonth: 1654.50,
      thisWeek: 441.25,
      avgPerDay: 60.52,
      itemsSoldMonth: 1043,
      avgSalePrice: 1.80,
      recentSales: [
        { item: 'Red Bull', qty: 2, time: '3:10 PM', revenue: 7.00 },
        { item: 'Water (16oz)', qty: 1, time: '2:55 PM', revenue: 1.50 },
        { item: 'Lay\'s Classic', qty: 1, time: '2:40 PM', revenue: 1.75 },
        { item: 'Snickers', qty: 1, time: '1:30 PM', revenue: 1.75 },
        { item: 'Gatorade Blue', qty: 2, time: '12:15 PM', revenue: 4.50 },
        { item: 'Kit Kat', qty: 1, time: '11:00 AM', revenue: 1.75 },
        { item: 'Trail Mix', qty: 1, time: '10:30 AM', revenue: 2.00 },
      ],
    },
  },
  {
    id: '3',
    name: 'Rec Center',
    location: 'Co-Rec – Lobby',
    address: '355 N Martin Jischke Dr, West Lafayette, IN 47907',
    buildingNotes: 'Enter Co-Rec through the main entrance on Martin Jischke Dr. The machine is in the main lobby on the left side, just past the front desk by the water fountains. Free parking in the Co-Rec lot directly out front.',
    status: 'offline',
    revenueToday: 0,
    itemsInStock: 67,
    alerts: 4,
    slots: [
      { id: 'A1', name: 'Lay\'s Classic', stock: 3, capacity: 10, price: 1.75, reorderUrl: 'https://www.costco.com' },
      { id: 'A2', name: 'Protein Bar', stock: 0, capacity: 8, price: 2.50, reorderUrl: 'https://www.costco.com' },
      { id: 'A3', name: 'Cheez-Its', stock: 8, capacity: 10, price: 1.50, reorderUrl: 'https://www.costco.com' },
      { id: 'B1', name: 'Water (16oz)', stock: 0, capacity: 12, price: 1.50, reorderUrl: 'https://www.costco.com' },
      { id: 'B2', name: 'Gatorade Blue', stock: 1, capacity: 12, price: 2.25, reorderUrl: 'https://www.costco.com' },
      { id: 'B3', name: 'Coconut Water', stock: 5, capacity: 8, price: 2.75, reorderUrl: 'https://www.costco.com' },
      { id: 'C1', name: 'Snickers', stock: 0, capacity: 10, price: 1.75, reorderUrl: 'https://www.costco.com' },
      { id: 'C2', name: 'KIND Bar', stock: 7, capacity: 10, price: 2.25, reorderUrl: 'https://www.costco.com' },
    ],
    weekSales: [
      { day: 'Mon', sales: 29 },
      { day: 'Tue', sales: 34 },
      { day: 'Wed', sales: 28 },
      { day: 'Thu', sales: 31 },
      { day: 'Fri', sales: 0 },
      { day: 'Sat', sales: 0 },
      { day: 'Sun', sales: 0 },
    ],
    peakHours: [
      { hour: '6am', sales: 14 },
      { hour: '8am', sales: 22 },
      { hour: '10am', sales: 11 },
      { hour: '12pm', sales: 8 },
      { hour: '4pm', sales: 19 },
      { hour: '6pm', sales: 25 },
      { hour: '8pm', sales: 17 },
    ],
    earnings: {
      monthToDate: 980.00,
      lastMonth: 1120.00,
      thisWeek: 182.50,
      avgPerDay: 31.61,
      itemsSoldMonth: 521,
      avgSalePrice: 1.88,
      recentSales: [
        { item: 'Gatorade Blue', qty: 1, time: 'Yesterday 8:12 PM', revenue: 2.25 },
        { item: 'KIND Bar', qty: 2, time: 'Yesterday 6:45 PM', revenue: 4.50 },
        { item: 'Water (16oz)', qty: 3, time: 'Yesterday 5:30 PM', revenue: 4.50 },
        { item: 'Snickers', qty: 1, time: 'Yesterday 4:00 PM', revenue: 1.75 },
      ],
    },
  },
];
